// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mpcxzgufotmzqovzorgx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wY3h6Z3Vmb3RtenFvdnpvcmd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NDMwNzUsImV4cCI6MjA2ODQxOTA3NX0.miiBlg19EmRdTKQ4S4vhmmaV2ZkQ9ys9bOrPNy92RrQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});